# Makefile for observ viewer demo
#
# This code is part of the Diderot Project (http://diderot-language.cs.uchicago.edu)
#
# COPYRIGHT (c) 2015 The University of Chicago
# All rights reserved.
#

TARGET		= observ

build:	$(TARGET)

include ../../data/makedefs.gmk
include ../../data/makerules_so.gmk

override DIDEROTC_FLAGS	+= --namespace=observ

